all:
  hosts:
    master-1:
      ansible_host: 10.166.0.9
      ip: 10.166.0.9
      access_ip: 10.166.0.9
    node1:
      ansible_host: 10.182.0.6
      ip: 10.182.0.6
      access_ip: 10.182.0.6
    node2:
      ansible_host: 10.182.0.7
      ip: 10.182.0.7
      access_ip: 10.182.0.7
    node3:
      ansible_host: 10.182.0.8
      ip: 10.182.0.8
      access_ip: 10.182.0.8
  children:
    kube-master:
      hosts:
        master-1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube-master:
        kube_node:
    calico_rr:
      hosts: {}
